// Strings
// collection of characters is called a string
let name = "Harry";
console.log(name);
console.log(name[0]);
console.log(name[1]);
console.log(name[2]);
console.log(name[3]);
console.log(name[4]);
console.log(name.length);
// can also be created using single qoutes
let friend = "Abdullah";
console.log(friend);

//Template literals -> Part of Modern Js
// done using back tick can use both single and double qoutes too epic stuff

let dude1 = "Luffy";
let dude2 = "Zoro";
let sentence = `${dude1} is a friend of ${dude2}`;
console.log(sentence);

// Escape Sequence characters
/*
\n -> Newline
\t -> Tab
\r -> Carriage Return
*/
